default: &default
  pool: 5
  timeout: 5000
  encoding: utf8

development:
  adapter: sqlite3
  database: bemotion_db_development

test: &TEST
  adapter: sqlite3
  database: bemotion_db_test

production:
  adapter: postgresql
  encoding: utf8
  database: bemotion_db_production

cucumber:
  <<: *TEST
